[[redirects]]
  from = "https://hourlyrate.netlify.com/*"
  to = "https://hourlyrate.frontend.im/:splat"
  status = 301
  force = true

#[[redirects]]
#  from = "https://hourlyrate.frontend.im/*"
#  to = "https://hourlyrate.frontend.im/:splat"
#  status = 301
#  force = true